name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # In case C API is in a submodule

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential llvm-dev libclang-dev

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
